import type { Metadata } from 'next'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import Container from '@mui/material/Container';
import { Box } from '@mui/material';

export const metadata: Metadata = {
  title: '2024 у Киреевых - Рандомный Санта',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Box component="body">
        <AppRouterCacheProvider>
          <Container component="main" maxWidth={false}>
            {children}
          </Container>
        </AppRouterCacheProvider>
      </Box>
    </html>
  )
}
